### ISSUE TITLE
idk how to run it

### ISSUE THREAD

**Issue by salahmak** [kmvi/javascript-deobfuscator#3]
i know it looks like a stupid question but how can i run it  to make it deobfuscate my javascript codes ?

**Comment by 0x384c0** [comment]
I running this project with following commands:
`git clone https://github.com/kmvi/javascript-deobfuscator.git`
`cd javascript-deobfuscator`
`npm install`
`npm install typescript --save-dev`
`npm install @types/node@latest`
`node_modules/.bin/tsc`
`node index.js`
